services:

    symfony-app-postgres:
        container_name: symfony-app-postgres
        image: postgres:16.2-alpine3.19
        restart: unless-stopped
        environment:
            - POSTGRES_DB=database
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
        ports:
            - '5432:5432'
        volumes:
            - ./infra/dev/postgres:/var/lib/postgresql/data:rw

    symfony-app-php:
        container_name: symfony-app-php
        image: symfony-app:latest
        restart: unless-stopped
        environment:
            - APP_NAME=symfony_app
            - APP_ENV=dev
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/app
            - ./infra/dev/nginx/logs:/var/log/nginx
            - ./infra/dev/supervisord/logs:/var/log/supervisor
            - ./infra/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./infra/dev/nginx/app.nginx.conf:/etc/nginx/conf.d/app.nginx.conf
            - ./infra/dev/nginx/supervisord.nginx.conf:/etc/conf.d/nginx/supervisord.nginx.conf
        depends_on:
            - symfony-app-postgres
