version: '3.8'

services:

    symfony-app-postgres:
        image: postgres:14-alpine
        container_name: symfony-app-postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DB=database
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
        ports:
            - '5444:5432'
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data:rw

    symfony-app-php:
        build:
            context: ./docker/php
            target: symfony-app-common
        container_name: symfony-app-php
        restart: unless-stopped
        volumes:
            - ./app:/var/www/app
        depends_on:
            - symfony-app-postgres

    symfony-app-nginx:
        image: nginx:stable-alpine
        container_name: symfony-app-nginx
        restart: unless-stopped
        ports:
            - '8080:80'
        volumes:
            - ./app:/var/www/app
            - ./docker/logs:/var/log/nginx
            - ./docker/nginx/symfony-app.nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - symfony-app-php